### ISSUE TITLE
[BUG] "Render" parameter in BaseAgent has unclear meaning.

### ISSUE THREAD

**Issue by iveta331** [liuzuxin/fsrl#1]
### Required prerequisites

- [X] I have read the documentation <https://fsrl.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/liuzuxin/fsrl/issues) and [Discussions](https://github.com/liuzuxin/fsrl/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/liuzuxin/fsrl/discussions/new).

### What version of FSRL are you using?

0.1.0

### System and environment information

I guess this is not relevant for this specific problem, but I installed fsrl according to the instructions here on github and I'm using python version 3.8

### Problem description

In BaseAgent "collect" method the _render_ parameter is described as "render (bool) – Whether to render the environment during evaluation, defaults to False". However looking at the code, the render is later called only in the collector's (FastCollector in this case) "collect" method, but there the meaning of _render_ is "render (float) – the sleep time between rendering consecutive frames. Default to None (no rendering)."

### Reproducible example code

This can be observed for example when running eval_ppol_agent.py from examples folder.

**Comment by Ja4822** [comment]
The "render" parameter in BaseAgent and FastCollector is now consistent. To render the environment, simply set "render" to be True.

**Comment by Ja4822** [comment]
The rendering bugs in Bullet-Safety-Gym envs are now fixed. Please reinstall the package from [here](https://github.com/liuzuxin/Bullet-Safety-Gym) if you wish to use these envs for rendering.

**Comment by iveta331** [comment]
Thanks, it works fine now :)
